language: java   # because we use Maven

os:
  - linux

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

env:
  matrix:
    - SCALA_VERSION=2.10
    - SCALA_VERSION=2.11

before_install:
  - cd /home/travis
  - wget http://histogrammar.org/m2-repository.tgz
  - tar -xzvf m2-repository.tgz
  - cd -
  - pwd

script: mvn install -P scala-${SCALA_VERSION}
